---
chdir: '/workspace/test_rails_crud'
environment: production
address: 0.0.0.0
port: 6661
timeout: 30
log: log/pids/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 30
server: 1
daemonize: true

